Add padded base64url payload string
google/jwt_verify_lib pull request #60
Opened 2021-01-18 03:19 UTC by TAOXUY

This PR provides the base64url payload string with padding.

**Risk**: low. Just like the added unit tests, the new one with padding should be equivalent to the original one after decoding. Of course, only the original one should be used in the JWT verification.

**Context**: although padding is not required by base64 encoding [spec](https://tools.ietf.org/html/rfc4648#section-3.2), some decode [libraries](https://stackoverflow.com/questions/3302946/how-to-decode-base64-url-in-python) are not robust enough to handle the one without padding.

2021-01-18 03:20 UTC, TAOXUY commented
@qiwzhang, @nareddyt

2021-01-18 03:23 UTC, TAOXUY commented
https://github.com/GoogleCloudPlatform/esp-v2/issues/178

2021-01-19 17:54 UTC, qiwzhang requested changes
No,  I don't want such paddling code in this library.  This is library is for jwt verification, it doesn't need such padding code.  It may cause confusing. 

Such padding is required by http header when copying to it.  let us do such simple paddling  in the envoy jwt_authn.

2021-02-10 16:36 UTC, closed without merging

2021-02-10 16:37 UTC, TAOXUY commented
Replace with [PR](https://github.com/envoyproxy/envoy/pull/14779) in envoy